#!/usr/bin/env bash
# Made by Jesus Palencia
# Licence: GPL-2
LC_ALL=C

if ! [[ -f /usr/bin/gpg ]] || [[ $(dpkg --get-selections | grep -w "gnupg" | awk '{print $1}' | head -1) != gnupg ]]; then
	if [[ "$EUID" != "0" ]]; then
		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
		exit 1
	fi
	apt-get -q update
	apt-get -qy install gnupg gpgv
	echo "Instalacion finalizada..."
	exit 0
fi

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: No debe ser root.\e[00m"
	exit 1
fi

if ! [[ -f $HOME/.gnupg/gpg.conf.old ]]; then
	mv -f $HOME/.gnupg/gpg.conf $HOME/.gnupg/gpg.conf.old
	echo "keyserver hkp://pool.sks-keyservers.net" > $HOME/.gnupg/gpg.conf
	echo "fixed-list-mode" >> $HOME/.gnupg/gpg.conf
	echo "keyid-format 0xlong" >> $HOME/.gnupg/gpg.conf
	echo "with-fingerprint" >> $HOME/.gnupg/gpg.conf
	echo "personal-digest-preferences SHA512 SHA384 SHA256 SHA224" >> $HOME/.gnupg/gpg.conf
	echo "default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 BZIP2 ZLIB ZIP Uncompressed" >> $HOME/.gnupg/gpg.conf
	echo "use-agent" >> $HOME/.gnupg/gpg.conf
	echo "verify-options show-uid-validity" >> $HOME/.gnupg/gpg.conf
	echo "list-options show-uid-validit" >> $HOME/.gnupg/gpg.conf
	echo "sig-notation issuer-fpr@notations.openpgp.fifthhorseman.net=%g" >> $HOME/.gnupg/gpg.conf
	echo "cert-digest-algo SHA512" >> $HOME/.gnupg/gpg.conf
	echo "keyserver-options no-honor-keyserver-url" >> $HOME/.gnupg/gpg.conf
fi

echo "Finalizado..."
